name: pentathlon_odd
description: App para la Gymkhana ODS de 3º ESO.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # --- FIREBASE (El Cerebro) ---
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0  # Para que los alumnos se registren
  cloud_firestore: ^4.14.0 # Base de datos para los equipos y puntos
  
  # --- OTRAS HERRAMIENTAS ---
  go_router: ^12.0.0      # Navegación moderna
  google_fonts: ^6.1.0    # Tipografía estilo "Neo-Brutalism"
  mobile_scanner: ^3.5.0  # Para los códigos QR
  provider: ^6.0.5        # Gestión de estado
  url_launcher: ^6.2.1    # Abrir vídeos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
